repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
    -   id: terraform_fmt
    -   id: terraform_tflint
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
